name: Build

on:
  push:
    branches:
      - master

env:
  IMAGE: docker.io/charlieegan3/dev-machine

jobs:
  x86:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2

      - name: Build dotfile archive
        run: |
          make archive_dotfiles

      - name: Build machine image
        run: |
          curl -LO https://releases.hashicorp.com/packer/1.5.5/packer_1.5.5_linux_amd64.zip
          unzip *.zip
          sudo mv packer /usr/local/bin/packer

          export B64_GPG_PUB="${{ secrets.B64_GPG_PUB }}"
          export B64_GPG_PRIV="${{ secrets.B64_GPG_PRIV }}"
          export B64_ID_RSA_PUB="${{ secrets.B64_ID_RSA }}"
          export B64_ID_RSA="${{ secrets.B64_ID_RSA }}"
          export DIGITALOCEAN_API_TOKEN="${{ secrets.DIGITALOCEAN_API_TOKEN }}"
          export COMMIT_SHA="${{ github.sha }}"
          export PASSWORD="${{ secrets.PASSWORD }}"
          packer validate packer.json
          packer build    packer.json

      - name: Remove old images
        run: |
          curl -LO https://github.com/digitalocean/doctl/releases/download/v1.39.0/doctl-1.39.0-linux-amd64.tar.gz
          tar -zxf doctl-1.39.0-linux-amd64.tar.gz
          sudo mv doctl /usr/local/bin/doctl
          sudo apt-get install -y moreutils

          doctl auth init -t ${{ secrets.DIGITALOCEAN_API_TOKEN }}
          doctl compute image list -o json \
            | jq -r '[.[] | .id][0:-2] | .[]' \
            | ifne xargs -n 1 doctl compute image delete -f
