name: Build

on:
  push:
    branches: [ master ]

jobs:
  Hetzner:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Image
      env:
        HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        make COMMIT_SHA="$GITHUB_SHA" build
