name: Build

on:
  push:
    branches: [ master ]

jobs:
  images:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Image
      env:
        HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
        PASSWORD: ${{ secrets.PASSWORD }}
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        GOOGLE_JSON: ${{ secrets.GOOGLE_JSON }}
        GOOGLE_APPLICATION_CREDENTIALS: google.json
      run: |
        echo "$GOOGLE_JSON" | base64 -d > google.json
        make COMMIT_SHA="$GITHUB_SHA" build
