name: Build

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 6 * * *'

env:
  IMAGE: docker.io/charlieegan3/dev-machine

jobs:
  x86:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2

      - name: Install packer
        run: |
          make install_packer

      - name: Build machine image
        run: |
          export B64_GPG_PRIV="${{ secrets.B64_GPG_PRIV }}"
          export B64_GPG_PUB="${{ secrets.B64_GPG_PUB }}"
          export B64_ID_RSA="${{ secrets.B64_ID_RSA }}"
          export B64_ID_RSA_PUB="${{ secrets.B64_ID_RSA_PUB }}"
          export COMMIT_SHA="${{ github.sha }}"
          export HETZNER_TOKEN="${{ secrets.HETZNER_TOKEN }}"
          export GITHUB_ACCESS_TOKEN="${{ secrets.GITHUB_ACCESS_TOKEN }}"
          export PASSWORD="${{ secrets.PASSWORD }}"
          export PUSHOVER_TOKEN="${{ secrets.PUSHOVER_TOKEN }}"
          export PUSHOVER_USER="${{ secrets.PUSHOVER_USER }}"

          make build
