name: Checks

on:
  schedule:
  - cron: "0 3 * * *"
  workflow_dispatch:
    inputs: {}

jobs:
  assert_no_instances:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Assert No Instances
      env:
        HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
      run: |
        curl -LO https://github.com/hetznercloud/cli/releases/download/v1.19.1/hcloud-linux-amd64.tar.gz
        tar -xf hcloud-linux-amd64.tar.gz
        ./hack/assert_no_instances.rb
